from enum import Enum

class EnvReaderEnum(Enum):
    LOCALDEV = 'INVMON_LOCAL_DEV'

    PYROSCOPEENABLED = "INVMON_PYROSCOPE_ENABLED"
    PYROSCOPESERVERADDRESS = "INVMON_PYROSCOPE_SERVER_ADDRESS"

    LOGLEVEL = "INVMON_LOG_LEVEL"

    SMTPHOST = "INVMON_SMTP_HOST"
    SMTPPORT = "INVMON_SMTP_PORT"
    SMTPUSERNAME = "INVMON_SMTP_USERNAME"
    SMTPPASSWORD = "INVMON_SMTP_PASSWORD"

    DATABASENAME = "INVMON_DATABASE_NAME"
    DATABASETYPE = "INVMON_DATABASE_TYPE"
    DATABASEUSERNAME = "INVMON_DATABASE_USERNAME"
    DATABASEPASSWORD = "INVMON_DATABASE_PASSWORD"
    DATABASEHOST = "INVMON_DATABASE_HOST"